"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type LanguageCode =
  | "en"
  | "es"
  | "fr"
  | "pt"
  | "zh"
  | "ja"
  | "ko"
  | "ar"
  | "vi"
  | "th"
  | "bn"
  | "my";

export interface LanguageItem {
  code: LanguageCode;
  label: string; // Native name
}

export const SUPPORTED_LANGUAGES: LanguageItem[] = [
  { code: "en", label: "English" },
  { code: "es", label: "Español" },
  { code: "fr", label: "Français" },
  { code: "pt", label: "Português" },
  { code: "zh", label: "中文" },
  { code: "ja", label: "日本語" },
  { code: "ko", label: "한국어" },
  { code: "ar", label: "العربية" },
  { code: "vi", label: "Tiếng Việt" },
  { code: "th", label: "ไทย" },
  { code: "bn", label: "বাংলা" },
  { code: "my", label: "မြန်မာ" },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Nav
    "nav.leaderboard": "Leaderboard",
    "nav.companies": "Companies",
    "nav.docs": "Docs",
    "nav.about": "About",
    "nav.faq": "FAQ",
    "nav.live": "LIVE",

    // Live Index Banner
    "index.title": "SuperRich Real-Time Wealth Index",
    "index.tracking": "Tracking {count} Billionaires Worldwide",
    "index.syncing": "Syncing Live Feed...",
    "index.updated": "Updated {time}",
    "index.refreshTitle": "Refresh Real-Time Market Valuations",

    // Gainers & Losers
    "gainers.title": "Biggest Gainers",
    "gainers.subtitle": "Gains reflect daily net worth changes",
    "losers.title": "Biggest Losers",
    "losers.subtitle": "Losses reflect daily net worth changes",
    "gainers.loading": "Loading real-time gainers...",
    "losers.loading": "Loading real-time losers...",

    // Controls & Filters
    "filter.searchPlaceholder": "Search billionaires, company...",
    "filter.searchCompany": "Search company, ticker (e.g. NVDA)...",
    "filter.sortRank": "Sort: Rank (#1 to Top)",
    "filter.sortWorthDesc": "Net Worth (High to Low)",
    "filter.sortWorthAsc": "Net Worth (Low to High)",
    "filter.sortGainers": "Top 24h Gainers",
    "filter.sortLosers": "Top 24h Losers",
    "filter.sortAgeAsc": "Age (Youngest First)",
    "filter.sortAgeDesc": "Age (Oldest First)",
    "filter.sortCapDesc": "Market Cap (Highest)",
    "filter.sortCapAsc": "Market Cap (Lowest)",
    "filter.industryAll": "Industry: All",
    "filter.ageAll": "Age: All",
    "filter.countryAll": "Country: All",
    "filter.genderAll": "Gender: All",
    "filter.allSectors": "All Sectors",
    "filter.men": "Men",
    "filter.women": "Women",
    "filter.showing": "Showing {current} of {total}",
    "filter.showingCompanies": "Showing {current} of 100 Companies",
    "filter.under50": "Under 50",
    "filter.age5064": "50 - 64",
    "filter.age65plus": "65+",

    // Table Headers
    "th.rank": "Rank",
    "th.name": "Name",
    "th.netWorth": "Real-Time Net Worth",
    "th.change24h": "24h Change",
    "th.residence": "Current Residence",
    "th.company": "Primary Company / Source",
    "th.marketCap": "Market Cap",
    "th.sharePrice": "Share Price",
    "th.sector": "Sector",

    // Badges & Labels
    "badge.trillionaire": "WORLD'S FIRST TRILLIONAIRE",
    "badge.privateHoldings": "Private Holdings",

    // Companies
    "companies.title": "Top 100 Most Valued Companies",
    "companies.subtitle": "Live enterprise market capitalizations, share prices, and cross-linked billionaire stakes",
    "companies.back": "Back to Top 100 Companies",
    "companies.share": "Share Profile",
    "companies.copied": "Link Copied!",
    "companies.mostValued": "#{rank} Most Valued Worldwide",
    "companies.liveCap": "Live Market Capitalization",
    "companies.enterpriseCap": "Enterprise Market Capitalization",
    "companies.peRatio": "P/E Ratio",
    "companies.annualRevenue": "Annual Revenue",
    "companies.founded": "Founded",
    "companies.employees": "Employees",
    "companies.exchange": "Exchange",
    "companies.overview": "Corporate Overview",
    "companies.divisions": "Core Business Divisions & Flagship Offerings",
    "companies.stakeholders": "Billionaire Stakeholders",
    "companies.stakeholdersTitle": "Billionaire Equity Ownership & Executive Control",
    "companies.financials": "Financial & Trading Multiples",

    // Profile Details
    "profile.overview": "Overview",
    "profile.timeline": "Timeline",
    "profile.stocks": "Stocks & Equity",
    "profile.assets": "Assets",
    "profile.social": "Social Media",
    "profile.legal": "Legal & Filings",
    "profile.emails": "Contact & Court Archives",
    "profile.verifiedProfiles": "Verified Profiles:",
    "profile.verifiedSocial": "Verified Social Presence",
    "profile.noSocials": "No active public social media accounts verified for this executive. Official statements are communicated through regulatory filings and corporate press releases.",
    "profile.source": "Source: SuperRich Real-Time Index",
    "profile.readWiki": "Read full article on Wikipedia",
    "profile.readGrok": "Read full article on Grokipedia",
    "profile.coreEquity": "Core Equity Stakes & Live Assets",
  },

  es: {
    "nav.leaderboard": "Clasificación",
    "nav.companies": "Empresas",
    "nav.docs": "Docs",
    "nav.about": "Acerca de",
    "nav.faq": "Preguntas",
    "nav.live": "EN VIVO",

    "index.title": "Índice de Riqueza en Tiempo Real SuperRich",
    "index.tracking": "Rastreando {count} Multimillonarios en Todo el Mundo",
    "index.syncing": "Sincronizando Feed en Vivo...",
    "index.updated": "Actualizado {time}",
    "index.refreshTitle": "Actualizar Valoraciones en Tiempo Real",

    "gainers.title": "Mayores Ganadores",
    "gainers.subtitle": "Las ganancias reflejan variaciones diarias de patrimonio",
    "losers.title": "Mayores Perdedores",
    "losers.subtitle": "Las pérdidas reflejan variaciones diarias de patrimonio",
    "gainers.loading": "Cargando mayores ganadores...",
    "losers.loading": "Cargando mayores perdedores...",

    "filter.searchPlaceholder": "Buscar multimillonarios, empresas...",
    "filter.searchCompany": "Buscar empresa, ticker (ej. NVDA)...",
    "filter.sortRank": "Ordenar: Rango (#1 a la cima)",
    "filter.sortWorthDesc": "Patrimonio (Mayor a Menor)",
    "filter.sortWorthAsc": "Patrimonio (Menor a Mayor)",
    "filter.sortGainers": "Mayores Ganancias 24h",
    "filter.sortLosers": "Mayores Pérdidas 24h",
    "filter.sortAgeAsc": "Edad (Menor Primero)",
    "filter.sortAgeDesc": "Edad (Mayor Primero)",
    "filter.sortCapDesc": "Cap. de Mercado (Mayor)",
    "filter.sortCapAsc": "Cap. de Mercado (Menor)",
    "filter.industryAll": "Industria: Todas",
    "filter.ageAll": "Edad: Todas",
    "filter.countryAll": "País: Todos",
    "filter.genderAll": "Género: Todos",
    "filter.allSectors": "Todos los Sectores",
    "filter.men": "Hombres",
    "filter.women": "Mujeres",
    "filter.showing": "Mostrando {current} de {total}",
    "filter.showingCompanies": "Mostrando {current} de 100 Empresas",
    "filter.under50": "Menores de 50",
    "filter.age5064": "50 - 64 años",
    "filter.age65plus": "65+ años",

    "th.rank": "Rango",
    "th.name": "Nombre",
    "th.netWorth": "Patrimonio en Tiempo Real",
    "th.change24h": "Cambio 24h",
    "th.residence": "Residencia Actual",
    "th.company": "Empresa Principal / Fuente",
    "th.marketCap": "Cap. de Mercado",
    "th.sharePrice": "Precio de Acción",
    "th.sector": "Sector",

    "badge.trillionaire": "PRIMER BILLONARIO DEL MUNDO",
    "badge.privateHoldings": "Participaciones Privadas",

    "companies.title": "Las 100 Empresas Más Valiosas",
    "companies.subtitle": "Capitalizaciones bursátiles en tiempo real, precios de acciones y participaciones",
    "companies.back": "Volver a las 100 Empresas",
    "companies.share": "Compartir Perfil",
    "companies.copied": "¡Enlace Copiado!",
    "companies.mostValued": "#{rank} Más Valiosa a Nivel Mundial",
    "companies.liveCap": "Capitalización de Mercado en Vivo",
    "companies.enterpriseCap": "Capitalización de Mercado Corporativa",
    "companies.peRatio": "Ratio P/E",
    "companies.annualRevenue": "Ingresos Anuales",
    "companies.founded": "Fundada",
    "companies.employees": "Empleados",
    "companies.exchange": "Bolsa",
    "companies.overview": "Descripción Corporativa",
    "companies.divisions": "Divisiones de Negocios y Productos Principales",
    "companies.stakeholders": "Accionistas Multimillonarios",
    "companies.stakeholdersTitle": "Propiedad de Acciones y Control Ejecutivo",
    "companies.financials": "Múltiplos Financieros y Bursátiles",

    "profile.overview": "Resumen",
    "profile.timeline": "Cronología",
    "profile.stocks": "Acciones y Participaciones",
    "profile.assets": "Activos",
    "profile.social": "Redes Sociales",
    "profile.legal": "Asuntos Legales",
    "profile.emails": "Contactos y Archivos Judiciales",
    "profile.verifiedProfiles": "Perfiles Verificados:",
    "profile.verifiedSocial": "Presencia Social Verificada",
    "profile.noSocials": "No hay cuentas públicas de redes sociales verificadas para este ejecutivo.",
    "profile.source": "Fuente: SuperRich Real-Time Index",
    "profile.readWiki": "Leer artículo completo en Wikipedia",
    "profile.readGrok": "Leer artículo completo en Grokipedia",
    "profile.coreEquity": "Participaciones Principales y Activos en Vivo",
  },

  fr: {
    "nav.leaderboard": "Classement",
    "nav.companies": "Entreprises",
    "nav.docs": "Docs",
    "nav.about": "À propos",
    "nav.faq": "FAQ",
    "nav.live": "EN DIRECT",

    "index.title": "Indice de Richesse en Temps Réel SuperRich",
    "index.tracking": "Suivi de {count} Milliardaires dans le Monde",
    "index.syncing": "Synchronisation en Direct...",
    "index.updated": "Mis à jour {time}",
    "index.refreshTitle": "Actualiser les Valorisations en Temps Réel",

    "gainers.title": "Plus Fortes Hausses",
    "gainers.subtitle": "Les hausses reflètent les variations quotidiennes",
    "losers.title": "Plus Fortes Baisses",
    "losers.subtitle": "Les baisses reflètent les variations quotidiennes",
    "gainers.loading": "Chargement des hausses...",
    "losers.loading": "Chargement des baisses...",

    "filter.searchPlaceholder": "Rechercher milliardaires, entreprises...",
    "filter.searchCompany": "Rechercher entreprise, symbole (ex: NVDA)...",
    "filter.sortRank": "Trier: Rang (#1 au sommet)",
    "filter.sortWorthDesc": "Fortune (Décroissant)",
    "filter.sortWorthAsc": "Fortune (Croissant)",
    "filter.sortGainers": "Plus Fortes Hausses 24h",
    "filter.sortLosers": "Plus Fortes Baisses 24h",
    "filter.sortAgeAsc": "Âge (Plus jeune d'abord)",
    "filter.sortAgeDesc": "Âge (Plus âgé d'abord)",
    "filter.sortCapDesc": "Capitalisation (Plus élevée)",
    "filter.sortCapAsc": "Capitalisation (Moins élevée)",
    "filter.industryAll": "Secteur: Tous",
    "filter.ageAll": "Âge: Tous",
    "filter.countryAll": "Pays: Tous",
    "filter.genderAll": "Genre: Tous",
    "filter.allSectors": "Tous les Secteurs",
    "filter.men": "Hommes",
    "filter.women": "Femmes",
    "filter.showing": "Affichage de {current} sur {total}",
    "filter.showingCompanies": "Affichage de {current} sur 100 Entreprises",
    "filter.under50": "Moins de 50 ans",
    "filter.age5064": "50 - 64 ans",
    "filter.age65plus": "65 ans et plus",

    "th.rank": "Rang",
    "th.name": "Nom",
    "th.netWorth": "Fortune Nette en Temps Réel",
    "th.change24h": "Variation 24h",
    "th.residence": "Résidence Actuelle",
    "th.company": "Entreprise Principale",
    "th.marketCap": "Capitalisation",
    "th.sharePrice": "Prix de l'action",
    "th.sector": "Secteur",

    "badge.trillionaire": "PREMIER TRILLIONNAIRE AU MONDE",
    "badge.privateHoldings": "Actifs Privés",

    "companies.title": "Top 100 des Entreprises les Plus Valorisées",
    "companies.subtitle": "Capitalisations boursières en temps réel, cours des actions et participations",
    "companies.back": "Retour aux 100 Entreprises",
    "companies.share": "Partager",
    "companies.copied": "Lien copié !",
    "companies.mostValued": "#{rank} Plus Grande Valeur Mondiale",
    "companies.liveCap": "Capitalisation Boursière en Direct",
    "companies.enterpriseCap": "Capitalisation Boursière",
    "companies.peRatio": "Ratio C/B",
    "companies.annualRevenue": "Chiffre d'Affaires Annuel",
    "companies.founded": "Création",
    "companies.employees": "Employés",
    "companies.exchange": "Bourse",
    "companies.overview": "Présentation de l'Entreprise",
    "companies.divisions": "Activités Principales et Produits Phares",
    "companies.stakeholders": "Actionnaires Milliardaires",
    "companies.stakeholdersTitle": "Actionnariat et Contrôle de Direction",
    "companies.financials": "Multiples Financiers et Boursiers",

    "profile.overview": "Aperçu",
    "profile.timeline": "Chronologie",
    "profile.stocks": "Actions & Participations",
    "profile.assets": "Actifs",
    "profile.social": "Réseaux Sociaux",
    "profile.legal": "Affaires Juridiques",
    "profile.emails": "Contacts & Archives Judiciaires",
    "profile.verifiedProfiles": "Profils Vérifiés :",
    "profile.verifiedSocial": "Présence Sociale Vérifiée",
    "profile.noSocials": "Aucun compte public vérifié sur les réseaux sociaux pour ce dirigeant.",
    "profile.source": "Source: SuperRich Real-Time Index",
    "profile.readWiki": "Lire l'article complet sur Wikipedia",
    "profile.readGrok": "Lire l'article complet sur Grokipedia",
    "profile.coreEquity": "Participations Clés et Actifs en Direct",
  },

  pt: {
    "nav.leaderboard": "Classificação",
    "nav.companies": "Empresas",
    "nav.docs": "Docs",
    "nav.about": "Sobre",
    "nav.faq": "Perguntas",
    "nav.live": "AO VIVO",

    "index.title": "Índice de Riqueza em Tempo Real SuperRich",
    "index.tracking": "Rastreando {count} Bilionários no Mundo",
    "index.syncing": "Sincronizando Feed ao Vivo...",
    "index.updated": "Atualizado {time}",
    "index.refreshTitle": "Atualizar Avaliações em Tempo Real",

    "gainers.title": "Maiores Altas",
    "gainers.subtitle": "Ganhos refletem mudanças diárias de patrimônio",
    "losers.title": "Maiores Baixas",
    "losers.subtitle": "Perdas refletem mudanças diárias de patrimônio",
    "gainers.loading": "Carregando maiores altas...",
    "losers.loading": "Carregando maiores baixas...",

    "filter.searchPlaceholder": "Pesquisar bilionários, empresas...",
    "filter.searchCompany": "Pesquisar empresa, código (ex: NVDA)...",
    "filter.sortRank": "Ordenar: Classificação (#1 ao topo)",
    "filter.sortWorthDesc": "Patrimônio (Maior para Menor)",
    "filter.sortWorthAsc": "Patrimônio (Menor para Maior)",
    "filter.sortGainers": "Maiores Altas 24h",
    "filter.sortLosers": "Maiores Baixas 24h",
    "filter.sortAgeAsc": "Idade (Mais jovem primeiro)",
    "filter.sortAgeDesc": "Idade (Mais velho primeiro)",
    "filter.sortCapDesc": "Valor de Mercado (Maior)",
    "filter.sortCapAsc": "Valor de Mercado (Menor)",
    "filter.industryAll": "Setor: Todos",
    "filter.ageAll": "Idade: Todas",
    "filter.countryAll": "País: Todos",
    "filter.genderAll": "Gênero: Todos",
    "filter.allSectors": "Todos os Setores",
    "filter.men": "Homens",
    "filter.women": "Mulheres",
    "filter.showing": "Mostrando {current} de {total}",
    "filter.showingCompanies": "Mostrando {current} de 100 Empresas",
    "filter.under50": "Menos de 50",
    "filter.age5064": "50 - 64 anos",
    "filter.age65plus": "65+ anos",

    "th.rank": "Posição",
    "th.name": "Nome",
    "th.netWorth": "Patrimônio em Tempo Real",
    "th.change24h": "Variação 24h",
    "th.residence": "Residência Atual",
    "th.company": "Empresa Principal / Fonte",
    "th.marketCap": "Valor de Mercado",
    "th.sharePrice": "Preço da Ação",
    "th.sector": "Setor",

    "badge.trillionaire": "PRIMEIRO TRILIONÁRIO DO MUNDO",
    "badge.privateHoldings": "Participações Privadas",

    "companies.title": "Top 100 Empresas Mais Valiosas",
    "companies.subtitle": "Capitalização de mercado em tempo real, preços de ações e participações",
    "companies.back": "Voltar para as 100 Empresas",
    "companies.share": "Compartilhar",
    "companies.copied": "Link Copiado!",
    "companies.mostValued": "#{rank} Mais Valiosa do Mundo",
    "companies.liveCap": "Capitalização em Tempo Real",
    "companies.enterpriseCap": "Valor de Mercado Corporativo",
    "companies.peRatio": "P/L",
    "companies.annualRevenue": "Receita Anual",
    "companies.founded": "Fundada",
    "companies.employees": "Funcionários",
    "companies.exchange": "Bolsa",
    "companies.overview": "Visão Geral Corporativa",
    "companies.divisions": "Divisões e Principais Ofertas",
    "companies.stakeholders": "Acionistas Bilionários",
    "companies.stakeholdersTitle": "Participação e Controle Executivo",
    "companies.financials": "Múltiplos Financeiros",

    "profile.overview": "Visão Geral",
    "profile.timeline": "Linha do Tempo",
    "profile.stocks": "Ações e Participações",
    "profile.assets": "Ativos",
    "profile.social": "Redes Sociais",
    "profile.legal": "Processos Jurídicos",
    "profile.emails": "Contatos e Arquivos da Justiça",
    "profile.verifiedProfiles": "Perfis Verificados:",
    "profile.verifiedSocial": "Presença Social Verificada",
    "profile.noSocials": "Nenhuma conta de rede social pública verificada para este executivo.",
    "profile.source": "Fonte: SuperRich Real-Time Index",
    "profile.readWiki": "Ler artigo completo na Wikipedia",
    "profile.readGrok": "Ler artigo completo na Grokipedia",
    "profile.coreEquity": "Participações Principais e Ativos em Tempo Real",
  },

  zh: {
    "nav.leaderboard": "富豪榜",
    "nav.companies": "全球企业",
    "nav.docs": "文档",
    "nav.about": "关于",
    "nav.faq": "常见问题",
    "nav.live": "实时",

    "index.title": "SuperRich 实时财富指数",
    "index.tracking": "追踪全球 {count} 位超级富豪",
    "index.syncing": "实时同步中...",
    "index.updated": "更新于 {time}",
    "index.refreshTitle": "刷新实时资产估值",

    "gainers.title": "涨幅最大",
    "gainers.subtitle": "涨幅反映单日净资产变动",
    "losers.title": "跌幅最大",
    "losers.subtitle": "跌幅反映单日净资产变动",
    "gainers.loading": "加载实时涨幅榜...",
    "losers.loading": "加载实时跌幅榜...",

    "filter.searchPlaceholder": "搜索富豪、公司、国家...",
    "filter.searchCompany": "搜索企业、股票代码 (如 NVDA)...",
    "filter.sortRank": "排序: 排名 (#1至前列)",
    "filter.sortWorthDesc": "净资产 (从高到低)",
    "filter.sortWorthAsc": "净资产 (从低到高)",
    "filter.sortGainers": "24小时涨幅榜",
    "filter.sortLosers": "24小时跌幅榜",
    "filter.sortAgeAsc": "年龄 (年轻优先)",
    "filter.sortAgeDesc": "年龄 (年长优先)",
    "filter.sortCapDesc": "市值 (从高到低)",
    "filter.sortCapAsc": "市值 (从低到高)",
    "filter.industryAll": "行业: 全部",
    "filter.ageAll": "年龄: 全部",
    "filter.countryAll": "国家: 全部",
    "filter.genderAll": "性别: 全部",
    "filter.allSectors": "全部行业板块",
    "filter.men": "男性",
    "filter.women": "女性",
    "filter.showing": "显示 {current} / 共 {total} 位",
    "filter.showingCompanies": "显示 {current} / 共 100 家企业",
    "filter.under50": "50岁以下",
    "filter.age5064": "50 - 64岁",
    "filter.age65plus": "65岁以上",

    "th.rank": "排名",
    "th.name": "姓名",
    "th.netWorth": "实时净资产",
    "th.change24h": "24小时变动",
    "th.residence": "现居住地",
    "th.company": "主要公司 / 资产来源",
    "th.marketCap": "总市值",
    "th.sharePrice": "股票现价",
    "th.sector": "所属板块",

    "badge.trillionaire": "全球首位万亿美元富豪",
    "badge.privateHoldings": "未公开持股",

    "companies.title": "全球最具价值 100 家企业",
    "companies.subtitle": "企业实时总市值、股价变动以及关联超级富豪持股数据",
    "companies.back": "返回百大企业榜单",
    "companies.share": "分享主页",
    "companies.copied": "链接已复制！",
    "companies.mostValued": "全球市值第 {rank} 名",
    "companies.liveCap": "实时总市值",
    "companies.enterpriseCap": "企业总市值",
    "companies.peRatio": "市盈率 P/E",
    "companies.annualRevenue": "年营业收入",
    "companies.founded": "创办年份",
    "companies.employees": "员工规模",
    "companies.exchange": "交易所",
    "companies.overview": "企业概况",
    "companies.divisions": "核心业务板块与旗舰产品",
    "companies.stakeholders": "超级富豪股东",
    "companies.stakeholdersTitle": "重要富豪持股比例与管理权限",
    "companies.financials": "财务数据与交易乘数",

    "profile.overview": "概览",
    "profile.timeline": "生平时间线",
    "profile.stocks": "股票与持股",
    "profile.assets": "核心资产",
    "profile.social": "社交媒体",
    "profile.legal": "法律诉讼与监管档案",
    "profile.emails": "联络方式与法庭公开文档",
    "profile.verifiedProfiles": "官方认证账号：",
    "profile.verifiedSocial": "经官方核实的社交媒体账号",
    "profile.noSocials": "该高管未设立已认证的公开个人社交媒体账号，官方公告均通过监管备案及公司新闻稿发布。",
    "profile.source": "数据来源: SuperRich 实时指数",
    "profile.readWiki": "在维基百科阅读完整条目",
    "profile.readGrok": "在 Grokipedia 阅读完整条目",
    "profile.coreEquity": "核心股权与实时资产分布",
  },

  ja: {
    "nav.leaderboard": "長者番付",
    "nav.companies": "企業一覧",
    "nav.docs": "ドキュメント",
    "nav.about": "概要",
    "nav.faq": "FAQ",
    "nav.live": "ライブ",

    "index.title": "SuperRich リアルタイム富豪指数",
    "index.tracking": "世界の億万長者 {count} 名をリアルタイム追跡",
    "index.syncing": "ライブ同期中...",
    "index.updated": "更新: {time}",
    "index.refreshTitle": "時価評価を更新",

    "gainers.title": "最大の上昇",
    "gainers.subtitle": "変動は24時間の資産変化を反映",
    "losers.title": "最大の下落",
    "losers.subtitle": "変動は24時間の資産変化を反映",
    "gainers.loading": "上昇上位を読込中...",
    "losers.loading": "下落上位を読込中...",

    "filter.searchPlaceholder": "富豪、企業名で検索...",
    "filter.searchCompany": "企業名、ティッカー (例: NVDA) を検索...",
    "filter.sortRank": "並び順: 順位 (#1から順)",
    "filter.sortWorthDesc": "純資産 (高い順)",
    "filter.sortWorthAsc": "純資産 (低い順)",
    "filter.sortGainers": "24時間上昇率上位",
    "filter.sortLosers": "24時間下落率上位",
    "filter.sortAgeAsc": "年齢 (若い順)",
    "filter.sortAgeDesc": "年齢 (高い順)",
    "filter.sortCapDesc": "時価総額 (高い順)",
    "filter.sortCapAsc": "時価総額 (低い順)",
    "filter.industryAll": "業種: すべて",
    "filter.ageAll": "年齢: すべて",
    "filter.countryAll": "国: すべて",
    "filter.genderAll": "性別: すべて",
    "filter.allSectors": "すべてのセクター",
    "filter.men": "男性",
    "filter.women": "女性",
    "filter.showing": "{total}名中 {current}名を表示",
    "filter.showingCompanies": "100社中 {current}社を表示",
    "filter.under50": "50歳未満",
    "filter.age5064": "50 - 64歳",
    "filter.age65plus": "65歳以上",

    "th.rank": "順位",
    "th.name": "氏名",
    "th.netWorth": "リアルタイム純資産",
    "th.change24h": "24時間変動",
    "th.residence": "居住地",
    "th.company": "主要企業 / 資産源",
    "th.marketCap": "時価総額",
    "th.sharePrice": "株価",
    "th.sector": "セクター",

    "badge.trillionaire": "世界初の兆万長者",
    "badge.privateHoldings": "未公開資産",

    "companies.title": "世界時価総額上位 100 社",
    "companies.subtitle": "企業のリアルタイム時価総額、株価および富豪の保有比率",
    "companies.back": "企業一覧に戻る",
    "companies.share": "共有",
    "companies.copied": "リンクをコピーしました！",
    "companies.mostValued": "世界第 {rank} 位の企業価値",
    "companies.liveCap": "リアルタイム時価総額",
    "companies.enterpriseCap": "時価総額",
    "companies.peRatio": "PER",
    "companies.annualRevenue": "年間売上高",
    "companies.founded": "設立年",
    "companies.employees": "従業員数",
    "companies.exchange": "上場市場",
    "companies.overview": "企業概要",
    "companies.divisions": "主要事業部門および主力製品",
    "companies.stakeholders": "大株主富豪",
    "companies.stakeholdersTitle": "株式保有比率および経営権",
    "companies.financials": "財務倍率データ",

    "profile.overview": "概要",
    "profile.timeline": "年表",
    "profile.stocks": "保有株式",
    "profile.assets": "資産構成",
    "profile.social": "SNS",
    "profile.legal": "法的情報",
    "profile.emails": "連絡先・公式記録",
    "profile.verifiedProfiles": "認証済みアカウント:",
    "profile.verifiedSocial": "公式認証SNS",
    "profile.noSocials": "この経営者の認証済み公式SNSアカウントはありません。",
    "profile.source": "出典: SuperRich リアルタイム指数",
    "profile.readWiki": "Wikipedia で記事を読む",
    "profile.readGrok": "Grokipedia で記事を読む",
    "profile.coreEquity": "主要株式および保有資産",
  },

  ko: {
    "nav.leaderboard": "순위표",
    "nav.companies": "기업",
    "nav.docs": "문서",
    "nav.about": "소개",
    "nav.faq": "FAQ",
    "nav.live": "실시간",

    "index.title": "SuperRich 실시간 부호 지수",
    "index.tracking": "전 세계 {count}명의 억만장자 추적",
    "index.syncing": "실시간 동기화 중...",
    "index.updated": "{time} 업데이트됨",
    "index.refreshTitle": "실시간 자산 가치 새로고침",

    "gainers.title": "최대 상승자",
    "gainers.subtitle": "변동은 24시간 순자산 변화를 나타냅니다",
    "losers.title": "최대 하락자",
    "losers.subtitle": "변동은 24시간 순자산 변화를 나타냅니다",
    "gainers.loading": "상승 순위 불러오는 중...",
    "losers.loading": "하락 순위 불러오는 중...",

    "filter.searchPlaceholder": "억만장자, 기업 검색...",
    "filter.searchCompany": "기업명, 티커(예: NVDA) 검색...",
    "filter.sortRank": "정렬: 순위 (1위부터)",
    "filter.sortWorthDesc": "순자산 (높은 순)",
    "filter.sortWorthAsc": "순자산 (낮은 순)",
    "filter.sortGainers": "24시간 상승 상위",
    "filter.sortLosers": "24시간 하락 상위",
    "filter.sortAgeAsc": "나이 (어린 순)",
    "filter.sortAgeDesc": "나이 (많은 순)",
    "filter.sortCapDesc": "시가총액 (높은 순)",
    "filter.sortCapAsc": "시가총액 (낮은 순)",
    "filter.industryAll": "업종: 전체",
    "filter.ageAll": "연령: 전체",
    "filter.countryAll": "국가: 전체",
    "filter.genderAll": "성별: 전체",
    "filter.allSectors": "모든 섹터",
    "filter.men": "남성",
    "filter.women": "여성",
    "filter.showing": "{total}명 중 {current}명 표시",
    "filter.showingCompanies": "100개사 중 {current}개 표시",
    "filter.under50": "50세 미만",
    "filter.age5064": "50 - 64세",
    "filter.age65plus": "65세 이상",

    "th.rank": "순위",
    "th.name": "이름",
    "th.netWorth": "실시간 순자산",
    "th.change24h": "24시간 변동",
    "th.residence": "거주지",
    "th.company": "주요 기업 / 출처",
    "th.marketCap": "시가총액",
    "th.sharePrice": "주가",
    "th.sector": "섹터",

    "badge.trillionaire": "세계 최초의 조만장자",
    "badge.privateHoldings": "비공개 지분",

    "companies.title": "세계 최고 가치 100대 기업",
    "companies.subtitle": "실시간 시가총액, 주가 및 연계 억만장자 지분 현황",
    "companies.back": "100대 기업 목록으로 돌아가기",
    "companies.share": "공유",
    "companies.copied": "링크 복사 완료!",
    "companies.mostValued": "세계 시가총액 #{rank}위",
    "companies.liveCap": "실시간 시가총액",
    "companies.enterpriseCap": "기업 시가총액",
    "companies.peRatio": "PER",
    "companies.annualRevenue": "연간 매출",
    "companies.founded": "설립 연도",
    "companies.employees": "직원 수",
    "companies.exchange": "거래소",
    "companies.overview": "기업 개요",
    "companies.divisions": "주요 사업부 및 대표 제품",
    "companies.stakeholders": "억만장자 주요 주주",
    "companies.stakeholdersTitle": "지분율 및 경영권",
    "companies.financials": "재무 지표",

    "profile.overview": "개요",
    "profile.timeline": "연혁",
    "profile.stocks": "주식 및 지분",
    "profile.assets": "자산",
    "profile.social": "소셜 미디어",
    "profile.legal": "법적 분쟁",
    "profile.emails": "연락처 및 공공 문서",
    "profile.verifiedProfiles": "공식 인증 계정:",
    "profile.verifiedSocial": "인증된 소셜 미디어",
    "profile.noSocials": "이 임원의 인증된 공개 소셜 미디어 계정이 없습니다.",
    "profile.source": "출처: SuperRich 실시간 지수",
    "profile.readWiki": "위키백과에서 전체 기사 읽기",
    "profile.readGrok": "Grokipedia에서 전체 기사 읽기",
    "profile.coreEquity": "핵심 지분 및 실시간 자산",
  },

  ar: {
    "nav.leaderboard": "لوحة المتصدرين",
    "nav.companies": "الشركات",
    "nav.docs": "الوثائق",
    "nav.about": "حول",
    "nav.faq": "الأسئلة الشائعة",
    "nav.live": "مباشر",

    "index.title": "مؤشر ثروات سوبر ريتش في الوقت الفعلي",
    "index.tracking": "متابعة {count} مليارديراً حول العالم",
    "index.syncing": "جاري التزامن المباشر...",
    "index.updated": "تحديث: {time}",
    "index.refreshTitle": "تحديث التقييمات اللحظية",

    "gainers.title": "أكبر الرابحين",
    "gainers.subtitle": "الأرباح تعكس التغيرات اليومية في صافي الثروة",
    "losers.title": "أكبر الخاسرين",
    "losers.subtitle": "الخسائر تعكس التغيرات اليومية في صافي الثروة",
    "gainers.loading": "جاري تحميل الرابحين...",
    "losers.loading": "جاري تحميل الخاسرين...",

    "filter.searchPlaceholder": "ابحث عن المليارديرات والشركات...",
    "filter.searchCompany": "ابحث عن الشركات والرموز (مثل NVDA)...",
    "filter.sortRank": "الترتيب: الرتبة (من #1 للأعلى)",
    "filter.sortWorthDesc": "صافي الثروة (من الأعلى للأدنى)",
    "filter.sortWorthAsc": "صافي الثروة (من الأدنى للأعلى)",
    "filter.sortGainers": "أعلى الرابحين في 24 ساعة",
    "filter.sortLosers": "أعلى الخاسرين في 24 ساعة",
    "filter.sortAgeAsc": "العمر (الأصغر أولاً)",
    "filter.sortAgeDesc": "العمر (الأكبر أولاً)",
    "filter.sortCapDesc": "القيمة السوقية (الأعلى)",
    "filter.sortCapAsc": "القيمة السوقية (الأدنى)",
    "filter.industryAll": "القطاع: الكل",
    "filter.ageAll": "العمر: الكل",
    "filter.countryAll": "البلد: الكل",
    "filter.genderAll": "الجنس: الكل",
    "filter.allSectors": "جميع القطاعات",
    "filter.men": "رجال",
    "filter.women": "نساء",
    "filter.showing": "عرض {current} من {total}",
    "filter.showingCompanies": "عرض {current} من 100 شركة",
    "filter.under50": "أقل من 50",
    "filter.age5064": "50 - 64 سنة",
    "filter.age65plus": "65+ سنة",

    "th.rank": "الرتبة",
    "th.name": "الاسم",
    "th.netWorth": "صافي الثروة المباشر",
    "th.change24h": "تغير 24 ساعة",
    "th.residence": "الإقامة الحالية",
    "th.company": "الشركة الرئيسية / المصدر",
    "th.marketCap": "القيمة السوقية",
    "th.sharePrice": "سعر السهم",
    "th.sector": "القطاع",

    "badge.trillionaire": "أول تريليونير في العالم",
    "badge.privateHoldings": "أصول خاصة",

    "companies.title": "أكبر 100 شركة من حيث القيمة السوقية",
    "companies.subtitle": "القيمة السوقية اللحظية، أسعار الأسهم وحصص المليارديرات",
    "companies.back": "العودة إلى قائمة أفضل 100 شركة",
    "companies.share": "مشاركة",
    "companies.copied": "تم نسخ الرابط!",
    "companies.mostValued": "المرتبة #{rank} عالمياً في القيمة",
    "companies.liveCap": "القيمة السوقية المباشرة",
    "companies.enterpriseCap": "القيمة السوقية للشركة",
    "companies.peRatio": "مكرر الربحية",
    "companies.annualRevenue": "الإيرادات السنوية",
    "companies.founded": "سنة التأسيس",
    "companies.employees": "عدد الموظفين",
    "companies.exchange": "البورصة",
    "companies.overview": "نظرة عامة على الشركة",
    "companies.divisions": "القطاعات الرئيسية والمنتجات",
    "companies.stakeholders": "المساهمون المليارديرات",
    "companies.stakeholdersTitle": "نسبة الملكية والسيطرة التنفيذية",
    "companies.financials": "المؤشرات المالية",

    "profile.overview": "نظرة عامة",
    "profile.timeline": "الجدول الزمني",
    "profile.stocks": "الأسهم والحصص",
    "profile.assets": "الأصول",
    "profile.social": "وسائل التواصل",
    "profile.legal": "القضايا والملفات",
    "profile.emails": "جهات الاتصال والأرشيف القضائي",
    "profile.verifiedProfiles": "الحسابات الموثقة:",
    "profile.verifiedSocial": "حسابات التواصل الاجتماعي الموثقة",
    "profile.noSocials": "لا توجد حسابات تواصل اجتماعي عامة موثقة لهذا المسؤول التنفيذي.",
    "profile.source": "المصدر: مؤشر سوبر ريتش المباشر",
    "profile.readWiki": "قراءة المقال كاملاً على ويكيبيديا",
    "profile.readGrok": "قراءة المقال كاملاً على جروكيبيديا",
    "profile.coreEquity": "الحصص الرئيسية والأصول المباشرة",
  },

  vi: {
    "nav.leaderboard": "Bảng xếp hạng",
    "nav.companies": "Doanh nghiệp",
    "nav.docs": "Tài liệu",
    "nav.about": "Giới thiệu",
    "nav.faq": "Hỏi đáp",
    "nav.live": "TRỰC TIẾP",

    "index.title": "Chỉ số Tài sản Thời gian thực SuperRich",
    "index.tracking": "Theo dõi {count} Tỷ phú trên Toàn cầu",
    "index.syncing": "Đang đồng bộ trực tiếp...",
    "index.updated": "Cập nhật {time}",
    "index.refreshTitle": "Làm mới định giá thời gian thực",

    "gainers.title": "Tăng nhiều nhất",
    "gainers.subtitle": "Biến động phản ánh thay đổi tài sản trong ngày",
    "losers.title": "Giảm nhiều nhất",
    "losers.subtitle": "Biến động phản ánh thay đổi tài sản trong ngày",
    "gainers.loading": "Đang tải dữ liệu tăng...",
    "losers.loading": "Đang tải dữ liệu giảm...",

    "filter.searchPlaceholder": "Tìm kiếm tỷ phú, công ty...",
    "filter.searchCompany": "Tìm kiếm công ty, mã cổ phiếu (VD: NVDA)...",
    "filter.sortRank": "Sắp xếp: Thứ hạng (#1 đến cao nhất)",
    "filter.sortWorthDesc": "Tài sản (Cao đến Thấp)",
    "filter.sortWorthAsc": "Tài sản (Thấp đến Cao)",
    "filter.sortGainers": "Tăng mạnh nhất 24h",
    "filter.sortLosers": "Giảm mạnh nhất 24h",
    "filter.sortAgeAsc": "Tuổi (Trẻ nhất trước)",
    "filter.sortAgeDesc": "Tuổi (Lớn nhất trước)",
    "filter.sortCapDesc": "Vốn hóa (Cao nhất)",
    "filter.sortCapAsc": "Vốn hóa (Thấp nhất)",
    "filter.industryAll": "Ngành nghề: Tất cả",
    "filter.ageAll": "Độ tuổi: Tất cả",
    "filter.countryAll": "Quốc gia: Tất cả",
    "filter.genderAll": "Giới tính: Tất cả",
    "filter.allSectors": "Tất cả các ngành",
    "filter.men": "Nam",
    "filter.women": "Nữ",
    "filter.showing": "Hiển thị {current} trên {total}",
    "filter.showingCompanies": "Hiển thị {current} trên 100 Doanh nghiệp",
    "filter.under50": "Dưới 50 tuổi",
    "filter.age5064": "50 - 64 tuổi",
    "filter.age65plus": "65 tuổi trở lên",

    "th.rank": "Hạng",
    "th.name": "Họ và tên",
    "th.netWorth": "Tài sản Ròng Thời gian thực",
    "th.change24h": "Thay đổi 24h",
    "th.residence": "Nơi cư trú",
    "th.company": "Doanh nghiệp Chính / Nguồn",
    "th.marketCap": "Vốn hóa thị trường",
    "th.sharePrice": "Giá cổ phiếu",
    "th.sector": "Lĩnh vực",

    "badge.trillionaire": "NGƯỜI NGHÌN TỶ ĐÔ ĐẦU TIÊN THẾ GIỚI",
    "badge.privateHoldings": "Tài sản tư nhân",

    "companies.title": "Top 100 Doanh nghiệp Giá trị Nhất",
    "companies.subtitle": "Vốn hóa thị trường thời gian thực, giá cổ phiếu và tỷ lệ sở hữu của tỷ phú",
    "companies.back": "Quay lại danh sách 100 Doanh nghiệp",
    "companies.share": "Chia sẻ",
    "companies.copied": "Đã sao chép liên kết!",
    "companies.mostValued": "Doanh nghiệp giá trị thứ #{rank} toàn cầu",
    "companies.liveCap": "Vốn hóa Thị trường Trực tiếp",
    "companies.enterpriseCap": "Vốn hóa Doanh nghiệp",
    "companies.peRatio": "Hệ số P/E",
    "companies.annualRevenue": "Doanh thu Hàng năm",
    "companies.founded": "Năm thành lập",
    "companies.employees": "Nhân sự",
    "companies.exchange": "Sàn giao dịch",
    "companies.overview": "Tổng quan Doanh nghiệp",
    "companies.divisions": "Các mảng kinh doanh và sản phẩm chủ lực",
    "companies.stakeholders": "Cổ đông Tỷ phú",
    "companies.stakeholdersTitle": "Tỷ lệ cổ phần và quyền kiểm soát",
    "companies.financials": "Chỉ số tài chính và định giá",

    "profile.overview": "Tổng quan",
    "profile.timeline": "Dòng thời gian",
    "profile.stocks": "Cổ phiếu & Cổ phần",
    "profile.assets": "Tài sản",
    "profile.social": "Mạng xã hội",
    "profile.legal": "Hồ sơ pháp lý",
    "profile.emails": "Liên hệ & Hồ sơ tòa án",
    "profile.verifiedProfiles": "Tài khoản đã xác minh:",
    "profile.verifiedSocial": "Mạng Xã hội Đã Xác minh",
    "profile.noSocials": "Không có tài khoản mạng xã hội công khai nào được xác minh cho lãnh đạo này.",
    "profile.source": "Nguồn: Chỉ số Thời gian thực SuperRich",
    "profile.readWiki": "Đọc bài viết đầy đủ trên Wikipedia",
    "profile.readGrok": "Đọc bài viết đầy đủ trên Grokipedia",
    "profile.coreEquity": "Cổ phần cốt lõi và tài sản trực tiếp",
  },

  th: {
    "nav.leaderboard": "อันดับมหาเศรษฐี",
    "nav.companies": "บริษัทชั้นนำ",
    "nav.docs": "เอกสาร",
    "nav.about": "เกี่ยวกับ",
    "nav.faq": "คำถามพบบ่อย",
    "nav.live": "สด",

    "index.title": "ดัชนีความมั่งคั่งแบบเรียลไทม์ SuperRich",
    "index.tracking": "ติดตามมหาเศรษฐี {count} คนทั่วโลก",
    "index.syncing": "กำลังซิงค์ข้อมูลสด...",
    "index.updated": "อัปเดตเมื่อ {time}",
    "index.refreshTitle": "รีเฟรชมูลค่าตลาดแบบเรียลไทม์",

    "gainers.title": "ผู้ที่กำไรสูงสุด",
    "gainers.subtitle": "สะท้อนการเปลี่ยนแปลงมูลค่าทรัพย์สินรายวัน",
    "losers.title": "ผู้ที่ขาดทุนสูงสุด",
    "losers.subtitle": "สะท้อนการเปลี่ยนแปลงมูลค่าทรัพย์สินรายวัน",
    "gainers.loading": "กำลังโหลดข้อมูลกำไรสูงสุด...",
    "losers.loading": "กำลังโหลดข้อมูลขาดทุนสูงสุด...",

    "filter.searchPlaceholder": "ค้นหามหาเศรษฐี บริษัท...",
    "filter.searchCompany": "ค้นหาบริษัท รหัสหุ้น (เช่น NVDA)...",
    "filter.sortRank": "เรียงลำดับ: อันดับ (#1 จากสูงสุด)",
    "filter.sortWorthDesc": "ทรัพย์สิน (มากไปน้อย)",
    "filter.sortWorthAsc": "ทรัพย์สิน (น้อยไปมาก)",
    "filter.sortGainers": "กำไรสูงสุดใน 24 ชม.",
    "filter.sortLosers": "ขาดทุนสูงสุดใน 24 ชม.",
    "filter.sortAgeAsc": "อายุ (น้อยไปมาก)",
    "filter.sortAgeDesc": "อายุ (มากไปน้อย)",
    "filter.sortCapDesc": "มูลค่าตลาด (สูงสุด)",
    "filter.sortCapAsc": "มูลค่าตลาด (ต่ำสุด)",
    "filter.industryAll": "อุตสาหกรรม: ทั้งหมด",
    "filter.ageAll": "อายุ: ทั้งหมด",
    "filter.countryAll": "ประเทศ: ทั้งหมด",
    "filter.genderAll": "เพศ: ทั้งหมด",
    "filter.allSectors": "ทุกกลุ่มธุรกิจ",
    "filter.men": "ชาย",
    "filter.women": "หญิง",
    "filter.showing": "แสดง {current} จากทั้งหมด {total} คน",
    "filter.showingCompanies": "แสดง {current} จาก 100 บริษัท",
    "filter.under50": "อายุต่ำกว่า 50",
    "filter.age5064": "50 - 64 ปี",
    "filter.age65plus": "65 ปีขึ้นไป",

    "th.rank": "อันดับ",
    "th.name": "ชื่อ",
    "th.netWorth": "ทรัพย์สินสุทธิเรียลไทม์",
    "th.change24h": "เปลี่ยนแปลง 24 ชม.",
    "th.residence": "ที่พำนักปัจจุบัน",
    "th.company": "บริษัทหลัก / แหล่งที่มา",
    "th.marketCap": "มูลค่าหลักทรัพย์ตามราคาตลาด",
    "th.sharePrice": "ราคาหุ้น",
    "th.sector": "กลุ่มธุรกิจ",

    "badge.trillionaire": "เศรษฐีล้านล้านดอลลาร์คนแรกของโลก",
    "badge.privateHoldings": "สินทรัพย์ส่วนบุคคล",

    "companies.title": "100 บริษัทที่มีมูลค่าสูงที่สุดในโลก",
    "companies.subtitle": "มูลค่าตลาดแบบเรียลไทม์ ราคาหุ้น และสัดส่วนการถือหุ้นของมหาเศรษฐี",
    "companies.back": "กลับไปยัง 100 บริษัทชั้นนำ",
    "companies.share": "แชร์โปรไฟล์",
    "companies.copied": "คัดลอกลิงก์แล้ว!",
    "companies.mostValued": "อันดับ #{rank} บริษัทที่มีมูลค่าสูงสุดในโลก",
    "companies.liveCap": "มูลค่าตลาดสด",
    "companies.enterpriseCap": "มูลค่าองค์กร",
    "companies.peRatio": "อัตราส่วน P/E",
    "companies.annualRevenue": "รายได้ประจำปี",
    "companies.founded": "ปีก่อตั้ง",
    "companies.employees": "พนักงาน",
    "companies.exchange": "ตลาดหลักทรัพย์",
    "companies.overview": "ภาพรวมบริษัท",
    "companies.divisions": "สายธุรกิจหลักและผลิตภัณฑ์เด่น",
    "companies.stakeholders": "ผู้ถือหุ้นมหาเศรษฐี",
    "companies.stakeholdersTitle": "สัดส่วนการถือหุ้นและการควบคุม",
    "companies.financials": "ข้อมูลทางการเงินและอัตราส่วน",

    "profile.overview": "ภาพรวม",
    "profile.timeline": "ไทม์ไลน์ชีวิต",
    "profile.stocks": "หุ้นและสัดส่วนการลงทุน",
    "profile.assets": "สินทรัพย์",
    "profile.social": "โซเชียลมีเดีย",
    "profile.legal": "คดีความและเอกสารกฎหมาย",
    "profile.emails": "ข้อมูลติดต่อและเอกสารศาล",
    "profile.verifiedProfiles": "บัญชีที่ได้รับการยืนยัน:",
    "profile.verifiedSocial": "บัญชีโซเชียลมีเดียที่ผ่านการยืนยัน",
    "profile.noSocials": "ไม่มีบัญชีโซเชียลมีเดียสาธารณะที่ได้รับการยืนยันสำหรับผู้บริหารท่านนี้",
    "profile.source": "ที่มา: ดัชนีเรียลไทม์ SuperRich",
    "profile.readWiki": "อ่านบทความฉบับเต็มบน Wikipedia",
    "profile.readGrok": "อ่านบทความฉบับเต็มบน Grokipedia",
    "profile.coreEquity": "หุ้นหลักและสินทรัพย์เรียลไทม์",
  },

  bn: {
    "nav.leaderboard": "শীর্ষ তালিকা",
    "nav.companies": "কোম্পানি",
    "nav.docs": "নথি",
    "nav.about": "পরিচিতি",
    "nav.faq": "প্রশ্নোত্তর",
    "nav.live": "লাইভ",

    "index.title": "সুপাররিচ রিয়েল-টাইম সম্পদ সূচক",
    "index.tracking": "বিশ্বের {count} জন বিলিয়নিয়ারের তথ্য পর্যবেক্ষণ",
    "index.syncing": "লাইভ ডেটা সিঙ্ক হচ্ছে...",
    "index.updated": "আপডেট: {time}",
    "index.refreshTitle": "রিয়েল-টাইম বাজার মূল্য রিফ্রেশ করুন",

    "gainers.title": "শীর্ষ লাভবান",
    "gainers.subtitle": "লাভ দৈনিক মোট সম্পদের পরিবর্তন নির্দেশ করে",
    "losers.title": "শীর্ষ লোকসান",
    "losers.subtitle": "লোকসান দৈনিক মোট সম্পদের পরিবর্তন নির্দেশ করে",
    "gainers.loading": "লাভবানদের তালিকা লোড হচ্ছে...",
    "losers.loading": "লোকসানকারীদের তালিকা লোড হচ্ছে...",

    "filter.searchPlaceholder": "বিলিয়নিয়ার, কোম্পানি খুঁজুন...",
    "filter.searchCompany": "কোম্পানি, শেয়ার কোড (যেমন NVDA) খুঁজুন...",
    "filter.sortRank": "বাছাই: ক্রম (#১ থেকে শুরু)",
    "filter.sortWorthDesc": "সম্পদ (বেশি থেকে কম)",
    "filter.sortWorthAsc": "সম্পদ (কম থেকে বেশি)",
    "filter.sortGainers": "২৪ ঘণ্টায় শীর্ষ লাভবান",
    "filter.sortLosers": "২৪ ঘণ্টায় শীর্ষ লোকসান",
    "filter.sortAgeAsc": "বয়স (কনিষ্ঠ আগে)",
    "filter.sortAgeDesc": "বয়স (জ্যেষ্ঠ আগে)",
    "filter.sortCapDesc": "বাজার মূলধন (সর্বোচ্চ)",
    "filter.sortCapAsc": "বাজার মূলধন (সর্বনিম্ন)",
    "filter.industryAll": "শিল্প: সব",
    "filter.ageAll": "বয়স: সব",
    "filter.countryAll": "দেশ: সব",
    "filter.genderAll": "লিঙ্গ: সব",
    "filter.allSectors": "সমস্ত সেক্টর",
    "filter.men": "পুরুষ",
    "filter.women": "নারী",
    "filter.showing": "{total} জনের মধ্যে {current} জন প্রদর্শিত",
    "filter.showingCompanies": "১০০ কোম্পানির মধ্যে {current} টি প্রদর্শিত",
    "filter.under50": "৫০ বছরের নিচে",
    "filter.age5064": "৫০ - ৬৪ বছর",
    "filter.age65plus": "৬৫+ বছর",

    "th.rank": "ক্রম",
    "th.name": "নাম",
    "th.netWorth": "রিয়েল-টাইম মোট সম্পদ",
    "th.change24h": "২৪ ঘণ্টার পরিবর্তন",
    "th.residence": "বর্তমান বাসস্থান",
    "th.company": "প্রধান কোম্পানি / উৎস",
    "th.marketCap": "বাজার মূলধন",
    "th.sharePrice": "শেয়ারের মূল্য",
    "th.sector": "সেক্টর",

    "badge.trillionaire": "বিশ্বের প্রথম ট্রিলিয়নিয়ার",
    "badge.privateHoldings": "ব্যক্তিগত সম্পদ",

    "companies.title": "শীর্ষ ১০০ মূল্যবান কোম্পানি",
    "companies.subtitle": "লাইভ বাজার মূলধন, শেয়ার মূল্য এবং বিলিয়নিয়ারদের শেয়ারের তথ্য",
    "companies.back": "শীর্ষ ১০০ কোম্পানিতে ফিরে যান",
    "companies.share": "শেয়ার করুন",
    "companies.copied": "লিংক কপি করা হয়েছে!",
    "companies.mostValued": "বিশ্বের #{rank} শীর্ষ মূল্যবান কোম্পানি",
    "companies.liveCap": "লাইভ বাজার মূলধন",
    "companies.enterpriseCap": "মোট বাজার মূলধন",
    "companies.peRatio": "P/E অনুপাত",
    "companies.annualRevenue": "বার্ষিক আয়",
    "companies.founded": "প্রতিষ্ঠার বছর",
    "companies.employees": "কর্মচারী সংখ্যা",
    "companies.exchange": "শেয়ার বাজার",
    "companies.overview": "কোম্পানির বিবরণ",
    "companies.divisions": "প্রধান ব্যবসায়িক বিভাগ এবং পণ্য",
    "companies.stakeholders": "বিলিয়নিয়ার শেয়ারহোল্ডার",
    "companies.stakeholdersTitle": "শেয়ারের অংশ এবং পরিচালনা নিয়ন্ত্রণ",
    "companies.financials": "আর্থিক গুণক এবং উপাত্ত",

    "profile.overview": "সারসংক্ষেপ",
    "profile.timeline": "জীবনপঞ্জি",
    "profile.stocks": "শেয়ার ও অংশীদারিত্ব",
    "profile.assets": "সম্পদ",
    "profile.social": "সামাজিক যোগাযোগ",
    "profile.legal": "আইনি নথি ও মামলা",
    "profile.emails": "যোগাযোগ ও আদালতের নথি",
    "profile.verifiedProfiles": "যাচাইকৃত প্রোফাইল:",
    "profile.verifiedSocial": "যাচাইকৃত সামাজিক মাধ্যম",
    "profile.noSocials": "এই নির্বাহীর কোনো যাচাইকৃত উন্মুক্ত সামাজিক যোগাযোগ অ্যাকাউন্ট নেই।",
    "profile.source": "উৎস: সুপাররিচ রিয়েল-টাইম সূচক",
    "profile.readWiki": "উইকিপিডিয়ায় সম্পূর্ণ নিবন্ধ পড়ুন",
    "profile.readGrok": "গ্রোকিপিডিয়ায় সম্পূর্ণ নিবন্ধ পড়ুন",
    "profile.coreEquity": "প্রধান শেয়ার ও লাইভ সম্পদ",
  },

  my: {
    "nav.leaderboard": "ထိပ်တန်းစာရင်း",
    "nav.companies": "ကုမ္ပဏီများ",
    "nav.docs": "စာရွက်စာတမ်း",
    "nav.about": "အကြောင်း",
    "nav.faq": "အမေးအဖြေ",
    "nav.live": "တိုက်ရိုက်",

    "index.title": "SuperRich အချိန်နှင့်တပြေးညီ ကြွယ်ဝမှုညွှန်းကိန်း",
    "index.tracking": "ကမ္ဘာ့ဘီလျံနာ {count} ဦးကို စောင့်ကြည့်စစ်ဆေးခြင်း",
    "index.syncing": "တိုက်ရိုက်ချိတ်ဆက်နေသည်...",
    "index.updated": "{time} တွင် မွမ်းမံသည်",
    "index.refreshTitle": "အချိန်နှင့်တပြေးညီ ပိုင်ဆိုင်မှုပြန်လည်တွက်ချက်ရန်",

    "gainers.title": "အမြတ်အများဆုံးရရှိသူများ",
    "gainers.subtitle": "အမြတ်များသည် နေ့စဉ်ပိုင်ဆိုင်မှု အပြောင်းအလဲကို ဖော်ပြပါသည်",
    "losers.title": "အရှုံးအများဆုံးဖြစ်သူများ",
    "losers.subtitle": "အရှုံးများသည် နေ့စဉ်ပိုင်ဆိုင်မှု အပြောင်းအလဲကို ဖော်ပြပါသည်",
    "gainers.loading": "အမြတ်ရရှိသူများစာရင်း ခေါ်ယူနေသည်...",
    "losers.loading": "အရှုံးဖြစ်သူများစာရင်း ခေါ်ယူနေသည်...",

    "filter.searchPlaceholder": "ဘီလျံနာ၊ ကုမ္ပဏီ ရှာဖွေရန်...",
    "filter.searchCompany": "ကုမ္ပဏီ၊ စတော့အမည် (ဥပမာ NVDA) ရှာဖွေရန်...",
    "filter.sortRank": "စီစစ်ရန်: အဆင့် (#၁ မှ စတင်)",
    "filter.sortWorthDesc": "ပိုင်ဆိုင်မှု (အများမှ အနည်း)",
    "filter.sortWorthAsc": "ပိုင်ဆိုင်မှု (အနည်းမှ အများ)",
    "filter.sortGainers": "၂၄ နာရီအတွင်း အမြတ်အများဆုံး",
    "filter.sortLosers": "၂၄ နာရီအတွင်း အကျဆုံး",
    "filter.sortAgeAsc": "အသက် (အငယ်ဆုံးမှ စတင်)",
    "filter.sortAgeDesc": "အသက် (အကြီးဆုံးမှ စတင်)",
    "filter.sortCapDesc": "စျေးကွက်တန်ဖိုး (အများဆုံး)",
    "filter.sortCapAsc": "စျေးကွက်တန်ဖိုး (အနည်းဆုံး)",
    "filter.industryAll": "လုပ်ငန်းကဏ္ဍ: အားလုံး",
    "filter.ageAll": "အသက်အရွယ်: အားလုံး",
    "filter.countryAll": "နိုင်ငံ: အားလုံး",
    "filter.genderAll": "ကျား/မ: အားလုံး",
    "filter.allSectors": "ကဏ္ဍအားလုံး",
    "filter.men": "အမျိုးသား",
    "filter.women": "အမျိုးသမီး",
    "filter.showing": "{total} ဦးအနက် {current} ဦး ဖော်ပြနေသည်",
    "filter.showingCompanies": "ကုမ္ပဏီ ၁၀၀ အနက် {current} ခု ဖော်ပြနေသည်",
    "filter.under50": "အသက် ၅၀ အောက်",
    "filter.age5064": "၅၀ - ၆၄ နှစ်",
    "filter.age65plus": "၆၅ နှစ်နှင့်အထက်",

    "th.rank": "အဆင့်",
    "th.name": "အမည်",
    "th.netWorth": "အချိန်နှင့်တပြေးညီ ပိုင်ဆိုင်မှု",
    "th.change24h": "၂၄ နာရီပြောင်းလဲမှု",
    "th.residence": "လက်ရှိနေထိုင်ရာ",
    "th.company": "အဓိကကုမ္ပဏီ / ရင်းမြစ်",
    "th.marketCap": "စျေးကွက်တန်ဖိုး",
    "th.sharePrice": "စတော့ရှယ်ယာစျေး",
    "th.sector": "ကဏ္ဍ",

    "badge.trillionaire": "ကမ္ဘာ့ပထမဆုံး ထရီလျံနာ",
    "badge.privateHoldings": "ပုဂ္ဂလိကပိုင်ဆိုင်မှုများ",

    "companies.title": "ကမ္ဘာ့တန်ဖိုးအကြီးဆုံး ကုမ္ပဏီ ၁၀၀",
    "companies.subtitle": "အချိန်နှင့်တပြေးညီ စျေးကွက်တန်ဖိုး၊ ရှယ်ယာစျေးနှင့် ဘီလျံနာများ၏ ပိုင်ဆိုင်မှုရာခိုင်နှုန်း",
    "companies.back": "ကုမ္ပဏီ ၁၀၀ စာရင်းသို့ ပြန်သွားရန်",
    "companies.share": "မျှဝေရန်",
    "companies.copied": "လင့်ခ်ကို ကူးယူပြီးပါပြီ။",
    "companies.mostValued": "ကမ္ဘာ့အဆင့် #{rank} တန်ဖိုးအကြီးဆုံး",
    "companies.liveCap": "တိုက်ရိုက်စျေးကွက်တန်ဖိုး",
    "companies.enterpriseCap": "ကုမ္ပဏီတန်ဖိုး",
    "companies.peRatio": "P/E အချိုး",
    "companies.annualRevenue": "နှစ်စဉ်ဝင်ငွေ",
    "companies.founded": "တည်ထောင်သည့်နှစ်",
    "companies.employees": "ဝန်ထမ်းအရေအတွက်",
    "companies.exchange": "စတော့အိတ်ချိန်း",
    "companies.overview": "ကုမ္ပဏီအကျဉ်းချုပ်",
    "companies.divisions": "အဓိကလုပ်ငန်းကဏ္ဍများနှင့် ထုတ်ကုန်များ",
    "companies.stakeholders": "ဘီလျံနာ ရှယ်ယာရှင်များ",
    "companies.stakeholdersTitle": "ရှယ်ယာပိုင်ဆိုင်မှုနှင့် စီမံခန့်ခွဲမှုအာဏာ",
    "companies.financials": "ဘဏ္ဍာရေးအညွှန်းကိန်းများ",

    "profile.overview": "ခြုံငုံသုံးသပ်ချက်",
    "profile.timeline": "ဘဝမှတ်တမ်း",
    "profile.stocks": "စတော့ရှယ်ယာနှင့် ပိုင်ဆိုင်မှုများ",
    "profile.assets": "ပိုင်ဆိုင်မှုများ",
    "profile.social": "လူမှုကွန်ရက်",
    "profile.legal": "တရားဥပဒေဆိုင်ရာ မှတ်တမ်းများ",
    "profile.emails": "ဆက်သွယ်ရန်နှင့် တရားရုံးမှတ်တမ်းများ",
    "profile.verifiedProfiles": "အတည်ပြုပြီးသော အကောင့်များ:",
    "profile.verifiedSocial": "အတည်ပြုပြီးသော လူမှုကွန်ရက်စာမျက်နှာများ",
    "profile.noSocials": "ဤအမှုဆောင်အရာရှိအတွက် အတည်ပြုထားသော အများပြည်သူသုံး လူမှုကွန်ရက်အကောင့် မရှိပါ။",
    "profile.source": "ရင်းမြစ်: SuperRich အချိန်နှင့်တပြေးညီ ညွှန်းကိန်း",
    "profile.readWiki": "Wikipedia တွင် အပြည့်အစုံဖတ်ရန်",
    "profile.readGrok": "Grokipedia တွင် အပြည့်အစုံဖတ်ရန်",
    "profile.coreEquity": "အဓိကရှယ်ယာများနှင့် တိုက်ရိုက်ပိုင်ဆိုင်မှုများ",
  },
};

interface LanguageContextType {
  language: LanguageCode;
  languageItem: LanguageItem;
  setLanguage: (code: LanguageCode) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  languageItem: SUPPORTED_LANGUAGES[0],
  setLanguage: () => {},
  t: (key) => key,
});

export const LANGUAGE_STORAGE_KEY = "sr_selected_lang";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>("en");

  useEffect(() => {
    try {
      const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (saved) {
        // Try matching by code or by label
        const match = SUPPORTED_LANGUAGES.find(
          (l) => l.code === saved || l.label === saved
        );
        if (match) {
          setLanguageState(match.code);
        }
      }
    } catch {
      // Ignore during SSR or if storage is blocked
    }
  }, []);

  const setLanguage = (code: LanguageCode) => {
    setLanguageState(code);
    try {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, code);
    } catch {
      // Ignore
    }
  };

  const languageItem =
    SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];

  const t = (key: string, replacements?: Record<string, string | number>): string => {
    let str = TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
    if (replacements) {
      Object.entries(replacements).forEach(([k, v]) => {
        str = str.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, languageItem, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
